Some finetuning to get things working: - autodetection for CDK libraries.
git-svn-id: https://cdk.svn.sourceforge.net/svnroot/cdk/trunk/cdk@310 eb4e18e3-b210-0410-a6ab-dec725e4b171

diff --git a/packages/tar/cdk-bin/configure.in b/packages/tar/cdk-bin/configure.in
--- a/packages/tar/cdk-bin/configure.in
+++ b/packages/tar/cdk-bin/configure.in
@@ -9,6 +9,18 @@ AC_PROG_INSTALL
 AC_PROG_LN_S
 AC_PROG_MAKE_SET
 
+AC_MSG_CHECKING(for CDK libraries)
+if test -f "$prefix/lib/cdk/xerces-1.3.0.jar"
+then
+    CDKLIBDIR="$prefix"
+    AC_MSG_RESULT($CDKLIBDIR)
+else
+    AC_MSG_RESULT(no)
+	echo "The required libraries for CDK are not installed. Please download and install"
+	echo "the cdk-libs distribution."
+    exit 1
+fi
+
 AC_CHECK_PROG(HASJAVA, java, yes, no)
 if test "xyes" = "x$HASJAVA"
 then
